### ISSUE TITLE
cheat code

### ISSUE THREAD

**Issue by Horkyze** [Kixunil/bitcoin_parser_tutorial#1]
Ahoj, mozes prosim publishnut full rust (cheat) code?

Diki ;)

**Comment by Kixunil** [comment]
[Pushnuté](https://github.com/Kixunil/btc_parse_tutor-rust)

Sorry, že tak neskoro, mal som toho mega veľa. Zvyšok hodím neskôr.

**Comment by Horkyze** [comment]
Diki, toto sa podarilo aj mne zlepit z toho tutorialu, ten main() vsak nie
